In [1]:
import numpy as np

### NumPy Array Slicing

1. `[ i: j ]`
2. `[ i: j: k ]`

The basic slice syntax is `i: j: k` where `i` is the starting index, `j` is the stopping index, and `k` is the step `(k != 0)`. 

This selects the `m` elements (in the corresponding dimension) with index values `i, i + k, …, i + (m - 1)k` where `m = q + (r != 0)` and `q` and `r` are the quotient and remainder obtained by dividing `j - i` by `k: j - i = q k + r`, so that `i + (m - 1) k < j`. 

In [27]:
src = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

In [28]:
# slice elements from the index 1 to the end of the array
src[1:]

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10])

In [29]:
# from the index 4 to the end of the array
src[4:]

array([ 5,  6,  7,  8,  9, 10])

In [30]:
# from the index 1 to the index 3 (not included)
src[1:3]

array([2, 3])

In [31]:
# from the index 5 to the index 9 (not included)
src[5:9]

array([6, 7, 8, 9])

In [32]:
# from the index 2 to the index 9 (not included) with step 2
src[2:9:2]

array([3, 5, 7, 9])

In [33]:
# from the index 1 to the index 9 (not included) with step 4
src[1:9:4]

array([2, 6])

In [35]:
src[-3:]

array([ 8,  9, 10])

In [34]:
# from the index 3 from the end to index 1 from the end
src[-3:-1]

array([8, 9])

In [38]:
src[-6:-3]

array([5, 6, 7])